import { NextPage } from 'next';
import Table from 'components/Table';
import { useMemo } from 'react';
import { Column, SortByFn } from 'react-table';
import Layout from 'components/Layout';

export type Data = {
  id: string;
  firstName: string;
  lastName: string;
  email: string;
  gender: string;
  city: string;
  country: string;
  orderId: number;
};

const TablePage: NextPage = () => {
  const data: Data[] = useMemo(
    () => [
      {
        id: 'c22e2c32-7d3a-4c40-82e0-6e06b4a2cbf2',
        firstName: 'Reginald',
        lastName: 'Gawthrope',
        email: 'rgawthrope0@vk.com',
        gender: 'Genderqueer',
        city: 'Lachute',
        country: 'Canada',
        orderId: 1,
      },
      {
        id: '653dc1d9-cc2e-46fb-9cc4-e28013de4d84',
        firstName: 'Kirsten',
        lastName: 'Morrilly',
        email: 'kmorrilly1@ask.com',
        gender: 'Male',
        city: 'Illapel',
        country: 'Chile',
        orderId: 2,
      },
      {
        id: 'a3021f3f-adcd-4e98-aaec-e97d07c63143',
        firstName: 'August',
        lastName: 'Desesquelle',
        email: 'adesesquelle2@cbc.ca',
        gender: 'Male',
        city: 'Kayukembang',
        country: 'Indonesia',
        orderId: 3,
      },
      {
        id: 'df9a3e94-2c36-4f22-bdc7-8eaf4805fed3',
        firstName: 'Concordia',
        lastName: 'Shipp',
        email: 'cshipp3@networkadvertising.org',
        gender: 'Male',
        city: 'Baylo',
        country: 'Philippines',
        orderId: 4,
      },
      {
        id: 'd6f87522-8dfc-44a7-8e87-530a7193b041',
        firstName: 'Andriette',
        lastName: 'Frank',
        email: 'afrank4@ask.com',
        gender: 'Bigender',
        city: 'Cikuray',
        country: 'Indonesia',
        orderId: 5,
      },
      {
        id: '9e68c5dc-4dfb-4a27-be76-51d712383eb8',
        firstName: 'Orelie',
        lastName: "O'Tuohy",
        email: 'ootuohy5@baidu.com',
        gender: 'Female',
        city: 'Fengyuan',
        country: 'China',
        orderId: 6,
      },
      {
        id: '1916b28c-bbf1-40f1-a49b-bde40faf5a1e',
        firstName: 'Emelita',
        lastName: 'Saines',
        email: 'esaines6@amazon.co.jp',
        gender: 'Non-binary',
        city: 'Kut Chap',
        country: 'Thailand',
        orderId: 7,
      },
      {
        id: 'ca9b0480-0ea7-4baf-a632-ea32e685a9ee',
        firstName: 'Carmelle',
        lastName: 'Dumbrell',
        email: 'cdumbrell7@angelfire.com',
        gender: 'Female',
        city: 'Biritiba Mirim',
        country: 'Brazil',
        orderId: 8,
      },
      {
        id: '6c9b719f-77e7-445b-96d0-59e126f8edee',
        firstName: 'Benton',
        lastName: 'Dineen',
        email: 'bdineen8@columbia.edu',
        gender: 'Bigender',
        city: 'Salas',
        country: 'Peru',
        orderId: 9,
      },
      {
        id: 'bd6f3385-6665-4e27-bab4-80c0935dab4d',
        firstName: 'Bax',
        lastName: 'Inskipp',
        email: 'binskipp9@feedburner.com',
        gender: 'Genderqueer',
        city: 'Lupao',
        country: 'Philippines',
        orderId: 10,
      },
      {
        id: 'dd853548-d6ef-4807-891a-8e5124f12daa',
        firstName: 'Zahara',
        lastName: 'Bidmead',
        email: 'zbidmeada@netscape.com',
        gender: 'Male',
        city: 'Yuanqiao',
        country: 'China',
        orderId: 11,
      },
      {
        id: '1190bb8b-4acc-4992-8b90-1cec5f303668',
        firstName: 'Ema',
        lastName: 'Brierton',
        email: 'ebriertonb@dropbox.com',
        gender: 'Female',
        city: 'Lallayug',
        country: 'Philippines',
        orderId: 12,
      },
      {
        id: '249ce7cf-3d35-46a8-a466-ec0d92f7bc5d',
        firstName: 'Leonardo',
        lastName: 'McLeese',
        email: 'lmcleesec@npr.org',
        gender: 'Genderqueer',
        city: 'Jeziorany',
        country: 'Poland',
        orderId: 13,
      },
      {
        id: '7ae77a48-69d1-496a-81a0-e5579ed903ad',
        firstName: 'Alexio',
        lastName: 'Breed',
        email: 'abreedd@howstuffworks.com',
        gender: 'Polygender',
        city: 'Yamagata-shi',
        country: 'Japan',
        orderId: 14,
      },
      {
        id: '652c83ad-182a-46de-9aca-91b900cd52b0',
        firstName: 'Gabrielle',
        lastName: 'Howson',
        email: 'ghowsone@dropbox.com',
        gender: 'Non-binary',
        city: 'Gantang',
        country: 'China',
        orderId: 15,
      },
      {
        id: '0c2ea8f5-7172-4a5e-a170-5bb49f0b2bd6',
        firstName: 'Winni',
        lastName: 'Cornall',
        email: 'wcornallf@facebook.com',
        gender: 'Female',
        city: 'Bačka Topola',
        country: 'Serbia',
        orderId: 16,
      },
      {
        id: '2214ef79-d47b-40aa-942e-4b5208df1e56',
        firstName: 'Ryann',
        lastName: 'MacGaughie',
        email: 'rmacgaughieg@chicagotribune.com',
        gender: 'Female',
        city: 'Hưng Yên',
        country: 'Vietnam',
        orderId: 17,
      },
      {
        id: 'd7414d7a-1cc5-4ed4-b876-8d45142af592',
        firstName: 'Kipper',
        lastName: 'Purbrick',
        email: 'kpurbrickh@deliciousdays.com',
        gender: 'Genderqueer',
        city: 'São José dos Campos',
        country: 'Brazil',
        orderId: 18,
      },
      {
        id: 'a6fdeb21-a482-479a-9001-00eb16668dc1',
        firstName: 'Lonee',
        lastName: 'Stellman',
        email: 'lstellmani@edublogs.org',
        gender: 'Non-binary',
        city: 'Tobias Barreto',
        country: 'Brazil',
        orderId: 19,
      },
      {
        id: 'b76ca99f-1fb9-4932-8579-a21ed89cc64f',
        firstName: 'West',
        lastName: 'Younge',
        email: 'wyoungej@yellowbook.com',
        gender: 'Female',
        city: 'Taluncemara',
        country: 'Indonesia',
        orderId: 20,
      },
      {
        id: 'ee4d0061-fc74-4ec3-80f5-65c651b4e8f1',
        firstName: 'Jolyn',
        lastName: 'Fearick',
        email: 'jfearickk@flickr.com',
        gender: 'Non-binary',
        city: 'Boca Suno',
        country: 'Ecuador',
        orderId: 21,
      },
      {
        id: 'a23a7b17-2cb6-4bc9-beae-c7b6e0e9e738',
        firstName: 'Mahmud',
        lastName: 'Broy',
        email: 'mbroyl@nhs.uk',
        gender: 'Agender',
        city: 'Bayt Qād',
        country: 'Palestinian Territory',
        orderId: 22,
      },
      {
        id: 'f2420bcf-247b-4d75-8f8f-a32fb51c7135',
        firstName: 'Erl',
        lastName: 'Redwood',
        email: 'eredwoodm@pbs.org',
        gender: 'Bigender',
        city: 'Carrazeda de Ansiães',
        country: 'Portugal',
        orderId: 23,
      },
      {
        id: 'f5db2a2a-8390-4c23-96c7-89dda4d22668',
        firstName: 'Kaiser',
        lastName: 'Gamon',
        email: 'kgamonn@delicious.com',
        gender: 'Non-binary',
        city: 'Sukonolo Krajan',
        country: 'Indonesia',
        orderId: 24,
      },
      {
        id: 'bf720e73-e132-49d3-af35-988f1509214a',
        firstName: 'Garv',
        lastName: 'Kopfen',
        email: 'gkopfeno@illinois.edu',
        gender: 'Genderfluid',
        city: 'Pakenjeng',
        country: 'Indonesia',
        orderId: 25,
      },
      {
        id: 'b35529ee-536d-4e3d-b9f1-d24498e39da1',
        firstName: 'Alanna',
        lastName: 'Shirley',
        email: 'ashirleyp@163.com',
        gender: 'Female',
        city: 'Moramanga',
        country: 'Madagascar',
        orderId: 26,
      },
      {
        id: 'abe10689-d33d-45d8-9d92-a67d9fa96977',
        firstName: 'Clara',
        lastName: 'Cornil',
        email: 'ccornilq@yandex.ru',
        gender: 'Polygender',
        city: 'Złocieniec',
        country: 'Poland',
        orderId: 27,
      },
      {
        id: 'b3df7f5c-cba0-4ded-a877-d36c37015191',
        firstName: 'Dorthy',
        lastName: 'Loffill',
        email: 'dloffillr@sfgate.com',
        gender: 'Genderfluid',
        city: 'Bolgar',
        country: 'Russia',
        orderId: 28,
      },
      {
        id: '653481f4-806e-45d1-9bf8-d2a77412a780',
        firstName: 'Lottie',
        lastName: 'Hlavac',
        email: 'lhlavacs@foxnews.com',
        gender: 'Female',
        city: 'Marne-la-Vallée',
        country: 'France',
        orderId: 29,
      },
      {
        id: '454c000b-fbac-497b-b38c-4fe0557f7d2d',
        firstName: 'Patsy',
        lastName: 'Balducci',
        email: 'pbalduccit@adobe.com',
        gender: 'Genderqueer',
        city: 'New York City',
        country: 'United States',
        orderId: 30,
      },
      {
        id: '31f7bd0c-e4c0-4a90-b34c-80d512790c5f',
        firstName: 'Florette',
        lastName: 'Sans',
        email: 'fsansu@google.com.br',
        gender: 'Agender',
        city: 'Lapachito',
        country: 'Argentina',
        orderId: 31,
      },
      {
        id: '1da8d854-af13-4ffa-a447-0cc76e0cd087',
        firstName: 'Conchita',
        lastName: 'Jonson',
        email: 'cjonsonv@spiegel.de',
        gender: 'Male',
        city: 'Águas Formosas',
        country: 'Brazil',
        orderId: 32,
      },
      {
        id: '6ba8eb00-bbe8-4013-a6a9-b6ec9a1dafd5',
        firstName: 'Beverlie',
        lastName: 'Grzeszczak',
        email: 'bgrzeszczakw@yellowbook.com',
        gender: 'Bigender',
        city: 'Petiga',
        country: 'Indonesia',
        orderId: 33,
      },
      {
        id: 'e092c9b6-cb01-4944-9585-4ea82798e198',
        firstName: 'Myrvyn',
        lastName: 'Pepperell',
        email: 'mpepperellx@nifty.com',
        gender: 'Male',
        city: 'Callao',
        country: 'Peru',
        orderId: 34,
      },
      {
        id: 'f9bbaf62-c8ed-4c25-857c-c94dd727fdc5',
        firstName: 'Lesley',
        lastName: 'Lenham',
        email: 'llenhamy@behance.net',
        gender: 'Female',
        city: 'Jiuzhen',
        country: 'China',
        orderId: 35,
      },
      {
        id: 'eccf2c54-7ca5-4443-bab3-75d3f3ba5358',
        firstName: 'Donnajean',
        lastName: 'Deniso',
        email: 'ddenisoz@hubpages.com',
        gender: 'Female',
        city: 'Zagreb - Centar',
        country: 'Croatia',
        orderId: 36,
      },
      {
        id: '559f1d7d-e591-4614-bd9e-05d2bad79697',
        firstName: 'Rosalind',
        lastName: 'McGee',
        email: 'rmcgee10@yellowpages.com',
        gender: 'Bigender',
        city: 'Jeżów Sudecki',
        country: 'Poland',
        orderId: 37,
      },
      {
        id: '7419e502-d7ef-46b9-81cf-f262f0fd9993',
        firstName: 'Letta',
        lastName: 'Ragg',
        email: 'lragg11@google.com.au',
        gender: 'Bigender',
        city: 'Bacalan',
        country: 'Philippines',
        orderId: 38,
      },
      {
        id: '4eed0486-3aaa-4b44-9943-0b50036ce7fb',
        firstName: 'Hi',
        lastName: 'Rowen',
        email: 'hrowen12@independent.co.uk',
        gender: 'Genderqueer',
        city: 'Karney Shomron',
        country: 'Palestinian Territory',
        orderId: 39,
      },
      {
        id: 'd0bdb1f1-c564-435c-85ee-f25eacd7888f',
        firstName: 'Ev',
        lastName: 'Jaukovic',
        email: 'ejaukovic13@bing.com',
        gender: 'Non-binary',
        city: 'Beisijia',
        country: 'China',
        orderId: 40,
      },
      {
        id: 'd685995c-0de3-4a12-abab-3aae451c9252',
        firstName: 'Lance',
        lastName: 'Legonidec',
        email: 'llegonidec14@irs.gov',
        gender: 'Genderqueer',
        city: 'Aoqiao',
        country: 'China',
        orderId: 41,
      },
      {
        id: '9dc52bcc-3fab-477f-9187-18c1ea4d72ed',
        firstName: 'Tom',
        lastName: 'Sands-Allan',
        email: 'tsandsallan15@ucoz.com',
        gender: 'Male',
        city: 'Fuding',
        country: 'China',
        orderId: 42,
      },
      {
        id: 'ed95667d-d0dd-4dd6-8e3a-1bd17c2573fe',
        firstName: 'Cordie',
        lastName: 'Severy',
        email: 'csevery16@indiegogo.com',
        gender: 'Genderqueer',
        city: 'Tymoshivka',
        country: 'Ukraine',
        orderId: 43,
      },
      {
        id: 'c897f375-7a54-41cc-8e20-684029593c78',
        firstName: 'Davida',
        lastName: 'Picott',
        email: 'dpicott17@uol.com.br',
        gender: 'Bigender',
        city: 'Zhangdun',
        country: 'China',
        orderId: 44,
      },
      {
        id: 'e2b2770b-7f64-403d-96ed-0d7d906b47d3',
        firstName: 'Garrott',
        lastName: 'Kearton',
        email: 'gkearton18@google.fr',
        gender: 'Genderfluid',
        city: 'Hepingyizu',
        country: 'China',
        orderId: 45,
      },
      {
        id: 'abc1a1d9-0d94-4884-88c3-4fd7461e2b86',
        firstName: 'Ermentrude',
        lastName: 'Semeradova',
        email: 'esemeradova19@google.ru',
        gender: 'Genderfluid',
        city: 'Lokokrangan',
        country: 'Indonesia',
        orderId: 46,
      },
      {
        id: 'b58e05f1-c8bc-426e-8369-882f66baccc1',
        firstName: 'Kin',
        lastName: 'Wilgar',
        email: 'kwilgar1a@un.org',
        gender: 'Male',
        city: 'Al Jīzah',
        country: 'Egypt',
        orderId: 47,
      },
      {
        id: '2d6e129b-d5a3-4a12-92b3-f440f2a4049c',
        firstName: 'Alfons',
        lastName: 'Raynton',
        email: 'araynton1b@zimbio.com',
        gender: 'Genderqueer',
        city: 'Changfeng',
        country: 'China',
        orderId: 48,
      },
      {
        id: 'b750e5dd-05d0-404c-b5f8-c7e44851f01e',
        firstName: 'Laryssa',
        lastName: 'Gretton',
        email: 'lgretton1c@accuweather.com',
        gender: 'Male',
        city: 'Banjar Triwangsakeliki',
        country: 'Indonesia',
        orderId: 49,
      },
      {
        id: 'd9816b1d-c25a-4f75-aae2-1bb12456004b',
        firstName: 'Clo',
        lastName: 'Kasparski',
        email: 'ckasparski1d@bluehost.com',
        gender: 'Bigender',
        city: 'Futang',
        country: 'China',
        orderId: 50,
      },
      {
        id: '2ac2d20c-1c6c-4d7e-a8b2-4d26818a4728',
        firstName: 'Emanuele',
        lastName: 'Cantrill',
        email: 'ecantrill1e@google.fr',
        gender: 'Male',
        city: 'Deir Ḥannā',
        country: 'Israel',
        orderId: 51,
      },
      {
        id: '0afb1c89-4efb-4398-b814-9cdadc5c4129',
        firstName: 'Anneliese',
        lastName: 'Houchen',
        email: 'ahouchen1f@homestead.com',
        gender: 'Female',
        city: 'Barotac Viejo',
        country: 'Philippines',
        orderId: 52,
      },
      {
        id: 'eeeaa5d7-ff55-4ffd-85f4-4c7248cb9c20',
        firstName: 'Madison',
        lastName: 'Renshall',
        email: 'mrenshall1g@tinyurl.com',
        gender: 'Non-binary',
        city: 'Gandiaye',
        country: 'Senegal',
        orderId: 53,
      },
      {
        id: 'e763ec3f-cf36-4866-b430-d32bb4f986b1',
        firstName: 'Jefferey',
        lastName: 'Agutter',
        email: 'jagutter1h@fema.gov',
        gender: 'Genderqueer',
        city: 'Lupak',
        country: 'Indonesia',
        orderId: 54,
      },
      {
        id: '99c67dd5-4446-4e10-8591-86a0108f314b',
        firstName: 'Josephina',
        lastName: 'Chessum',
        email: 'jchessum1i@dmoz.org',
        gender: 'Male',
        city: 'Birmingham',
        country: 'United Kingdom',
        orderId: 55,
      },
      {
        id: '45fd58d3-0d11-41cd-aa84-2b20ed94b8a8',
        firstName: 'Melli',
        lastName: 'Ammer',
        email: 'mammer1j@tumblr.com',
        gender: 'Polygender',
        city: 'Kubangeceng',
        country: 'Indonesia',
        orderId: 56,
      },
      {
        id: '04bfbd59-cfd2-4d6d-b555-5f06e568ac0d',
        firstName: 'Saundra',
        lastName: 'Jozwiak',
        email: 'sjozwiak1k@nifty.com',
        gender: 'Bigender',
        city: 'Stodolishche',
        country: 'Russia',
        orderId: 57,
      },
      {
        id: '2ad83592-68ee-4faf-88ab-63958390b9ea',
        firstName: 'Stesha',
        lastName: 'Lippett',
        email: 'slippett1l@odnoklassniki.ru',
        gender: 'Genderqueer',
        city: 'Xincun',
        country: 'China',
        orderId: 58,
      },
      {
        id: 'fbde327b-1fa8-4af9-8445-d4f4b1157581',
        firstName: 'Joey',
        lastName: 'Marzele',
        email: 'jmarzele1m@si.edu',
        gender: 'Genderfluid',
        city: 'Corralito',
        country: 'Argentina',
        orderId: 59,
      },
      {
        id: '9da363ae-6597-48e2-a54c-e134805025ef',
        firstName: 'Oliy',
        lastName: 'Gauthorpp',
        email: 'ogauthorpp1n@elegantthemes.com',
        gender: 'Polygender',
        city: 'Lešná',
        country: 'Czech Republic',
        orderId: 60,
      },
      {
        id: '7f6508f6-4020-4be8-8b66-d2ef4fa1b6a2',
        firstName: 'Perrine',
        lastName: 'Emig',
        email: 'pemig1o@smugmug.com',
        gender: 'Genderqueer',
        city: 'Yuelai',
        country: 'China',
        orderId: 61,
      },
      {
        id: '2b802dab-43a4-49b8-bc54-039e86076aba',
        firstName: 'Jerald',
        lastName: 'Ashbrook',
        email: 'jashbrook1p@yandex.ru',
        gender: 'Polygender',
        city: 'Nanjie',
        country: 'China',
        orderId: 62,
      },
      {
        id: 'b048cf3b-a786-4c91-9de0-f2b751f3c244',
        firstName: 'Peterus',
        lastName: 'Humbles',
        email: 'phumbles1q@si.edu',
        gender: 'Non-binary',
        city: 'Mertani',
        country: 'Indonesia',
        orderId: 63,
      },
      {
        id: '73ed118f-b325-498d-80de-b6fe9a4fcb56',
        firstName: 'Brunhilde',
        lastName: 'Mertgen',
        email: 'bmertgen1r@so-net.ne.jp',
        gender: 'Bigender',
        city: 'Juanshui',
        country: 'China',
        orderId: 64,
      },
      {
        id: '9373a29a-2504-4c4a-823a-c31af0493a37',
        firstName: 'Joell',
        lastName: 'Root',
        email: 'jroot1s@scribd.com',
        gender: 'Female',
        city: 'Gimry',
        country: 'Russia',
        orderId: 65,
      },
      {
        id: 'bac2cea3-4597-4f64-93dd-1330bf360b56',
        firstName: 'Rainer',
        lastName: 'Norcross',
        email: 'rnorcross1t@networksolutions.com',
        gender: 'Female',
        city: 'Nangakeo',
        country: 'Indonesia',
        orderId: 66,
      },
      {
        id: '23cfa1b4-c632-4441-b516-4a0f3522ff75',
        firstName: 'Graham',
        lastName: 'Gianiello',
        email: 'ggianiello1u@dyndns.org',
        gender: 'Bigender',
        city: 'Matamey',
        country: 'Niger',
        orderId: 67,
      },
      {
        id: '8b1d4403-34f9-4d23-9267-e3344bbb1423',
        firstName: 'Lil',
        lastName: 'Martyns',
        email: 'lmartyns1v@illinois.edu',
        gender: 'Polygender',
        city: 'Misasi',
        country: 'Tanzania',
        orderId: 68,
      },
      {
        id: '6f29c5fa-7b75-4c16-b974-b53d8de7fd3e',
        firstName: 'Dulsea',
        lastName: 'Scahill',
        email: 'dscahill1w@wired.com',
        gender: 'Agender',
        city: 'Pitogo',
        country: 'Philippines',
        orderId: 69,
      },
      {
        id: 'dae1039a-6b4c-4ed5-bab6-3324aa0d2adf',
        firstName: 'Gray',
        lastName: 'Baribal',
        email: 'gbaribal1x@google.cn',
        gender: 'Male',
        city: 'Yishan',
        country: 'China',
        orderId: 70,
      },
      {
        id: 'fc0760b6-07cc-44ad-85be-cf7a29d06ff4',
        firstName: 'Bradford',
        lastName: 'Furst',
        email: 'bfurst1y@tiny.cc',
        gender: 'Male',
        city: 'Garhi Yāsīn',
        country: 'Pakistan',
        orderId: 71,
      },
      {
        id: 'e19a3675-8877-4472-9b7a-8f16dbb16188',
        firstName: 'Rene',
        lastName: 'Nand',
        email: 'rnand1z@mysql.com',
        gender: 'Male',
        city: 'Néa Róda',
        country: 'Greece',
        orderId: 72,
      },
      {
        id: 'ab6aeed0-7466-45a1-a11b-42326f9ced26',
        firstName: 'Meghann',
        lastName: 'Voas',
        email: 'mvoas20@shinystat.com',
        gender: 'Agender',
        city: 'Fafe',
        country: 'Portugal',
        orderId: 73,
      },
      {
        id: 'c3131d02-7d91-4afe-9d51-83ff66001bb8',
        firstName: 'Karina',
        lastName: 'Lympenie',
        email: 'klympenie21@topsy.com',
        gender: 'Agender',
        city: 'Khlong Sam Wa',
        country: 'Thailand',
        orderId: 74,
      },
      {
        id: 'fe2224c9-89a3-4adb-9940-156a819f1268',
        firstName: 'Dodie',
        lastName: 'Lucien',
        email: 'dlucien22@opera.com',
        gender: 'Genderqueer',
        city: 'Moguqi',
        country: 'China',
        orderId: 75,
      },
      {
        id: 'ed5f87ed-145b-4831-9d04-1917cc4905fe',
        firstName: 'Esme',
        lastName: 'Tackle',
        email: 'etackle23@privacy.gov.au',
        gender: 'Genderfluid',
        city: 'Kranjska Gora',
        country: 'Slovenia',
        orderId: 76,
      },
      {
        id: 'be1eab3d-6c82-4cae-8b2d-a2a84e76fda6',
        firstName: 'Innis',
        lastName: 'Redd',
        email: 'iredd24@prlog.org',
        gender: 'Polygender',
        city: 'Sơn Trà',
        country: 'Vietnam',
        orderId: 77,
      },
      {
        id: 'd108ff57-bf25-423c-babb-c886c5e240f9',
        firstName: 'Joanie',
        lastName: 'Tilio',
        email: 'jtilio25@usgs.gov',
        gender: 'Bigender',
        city: 'Huangdimiao',
        country: 'China',
        orderId: 78,
      },
      {
        id: 'd5d80842-48e4-444b-ba21-31fd4fddc242',
        firstName: 'Linell',
        lastName: 'Jankin',
        email: 'ljankin26@auda.org.au',
        gender: 'Polygender',
        city: 'Villa Ocampo',
        country: 'Argentina',
        orderId: 79,
      },
      {
        id: '9b8bb2e3-39fa-4ceb-8483-59164d64944d',
        firstName: 'Borg',
        lastName: 'Bossel',
        email: 'bbossel27@auda.org.au',
        gender: 'Genderfluid',
        city: 'Paccho',
        country: 'Peru',
        orderId: 80,
      },
      {
        id: '04417b4c-7334-4506-a930-98a3cd3ecbef',
        firstName: 'Alastair',
        lastName: 'Barrott',
        email: 'abarrott28@ucoz.com',
        gender: 'Polygender',
        city: 'Saint-Cloud',
        country: 'France',
        orderId: 81,
      },
      {
        id: 'fc64adce-9142-4113-a686-fd2cd3a18b52',
        firstName: 'Devlen',
        lastName: 'Riddell',
        email: 'driddell29@1und1.de',
        gender: 'Polygender',
        city: 'Jiuhua',
        country: 'China',
        orderId: 82,
      },
      {
        id: '3533ca5b-fb76-40de-9241-10258faae37b',
        firstName: 'Inger',
        lastName: 'Bean',
        email: 'ibean2a@europa.eu',
        gender: 'Bigender',
        city: 'Pavlodol’skaya',
        country: 'Russia',
        orderId: 83,
      },
      {
        id: 'ae0c3321-dab8-47bf-b60c-e4d7e19e9525',
        firstName: 'Van',
        lastName: 'Stanborough',
        email: 'vstanborough2b@last.fm',
        gender: 'Female',
        city: 'Diriá',
        country: 'Nicaragua',
        orderId: 84,
      },
      {
        id: 'b5042267-5e27-49f4-9bd6-fc2841791fa6',
        firstName: 'Luigi',
        lastName: 'Librey',
        email: 'llibrey2c@issuu.com',
        gender: 'Non-binary',
        city: 'Cortes',
        country: 'Philippines',
        orderId: 85,
      },
      {
        id: '6a08ff06-896a-4fa5-aad4-b31081851912',
        firstName: 'Correna',
        lastName: 'Essery',
        email: 'cessery2d@miibeian.gov.cn',
        gender: 'Non-binary',
        city: 'Bolian',
        country: 'China',
        orderId: 86,
      },
      {
        id: '98a49439-aeae-4ed7-9ee7-a3024b9c15c9',
        firstName: 'Augustus',
        lastName: 'Collings',
        email: 'acollings2e@home.pl',
        gender: 'Polygender',
        city: 'Baimiao',
        country: 'China',
        orderId: 87,
      },
      {
        id: 'a55e3274-dede-46ff-a81d-d5dd00727982',
        firstName: 'Ewart',
        lastName: 'Almack',
        email: 'ealmack2f@infoseek.co.jp',
        gender: 'Bigender',
        city: 'Kengkou',
        country: 'China',
        orderId: 88,
      },
      {
        id: '02c5fb4e-8f46-4b19-a398-a658e3dde1b0',
        firstName: 'Bail',
        lastName: 'Raw',
        email: 'braw2g@twitpic.com',
        gender: 'Bigender',
        city: 'Jingzi',
        country: 'China',
        orderId: 89,
      },
      {
        id: '047deb1d-ef9e-4751-9d30-1d24f5bff13d',
        firstName: 'Irena',
        lastName: 'Girault',
        email: 'igirault2h@paginegialle.it',
        gender: 'Genderqueer',
        city: 'Austin',
        country: 'United States',
        orderId: 90,
      },
      {
        id: '86926c42-64ba-49e2-83de-fdf8c0b36f56',
        firstName: 'Mercie',
        lastName: 'Hamnet',
        email: 'mhamnet2i@kickstarter.com',
        gender: 'Genderqueer',
        city: 'Pinhal General',
        country: 'Portugal',
        orderId: 91,
      },
      {
        id: '700517f1-f8bc-4ff0-b592-db4b9345da74',
        firstName: 'Rudiger',
        lastName: 'Spincke',
        email: 'rspincke2j@nps.gov',
        gender: 'Genderfluid',
        city: 'Vredenburg',
        country: 'South Africa',
        orderId: 92,
      },
      {
        id: 'd96ba58b-2531-4c3b-a55f-da68f77bd1c6',
        firstName: 'Lu',
        lastName: 'Girardi',
        email: 'lgirardi2k@tripadvisor.com',
        gender: 'Genderfluid',
        city: 'Erdaohe',
        country: 'China',
        orderId: 93,
      },
      {
        id: '11442434-1533-469f-aaa4-f2274b4de319',
        firstName: 'Lars',
        lastName: 'Mantram',
        email: 'lmantram2l@sciencedaily.com',
        gender: 'Female',
        city: 'Yessentukskaya',
        country: 'Russia',
        orderId: 94,
      },
      {
        id: 'f5df90e4-3cc7-4cca-88ea-0c29ab8493a7',
        firstName: 'Pinchas',
        lastName: 'Goede',
        email: 'pgoede2m@tamu.edu',
        gender: 'Female',
        city: 'Bijeli',
        country: 'Indonesia',
        orderId: 95,
      },
      {
        id: 'a828342e-fa39-4b49-8e7d-16114695cfb1',
        firstName: 'Dominique',
        lastName: 'McIvor',
        email: 'dmcivor2n@slashdot.org',
        gender: 'Agender',
        city: 'Xitiangezhuang',
        country: 'China',
        orderId: 96,
      },
      {
        id: '8a6a020d-e122-46c6-b0ca-9e040ac9949b',
        firstName: 'Theressa',
        lastName: 'Cahalan',
        email: 'tcahalan2o@arizona.edu',
        gender: 'Female',
        city: 'Chambishi',
        country: 'Zambia',
        orderId: 97,
      },
      {
        id: '9d2f22e4-7c08-4bf9-8c75-aff1b9cb8ee2',
        firstName: 'Mia',
        lastName: 'Effnert',
        email: 'meffnert2p@msn.com',
        gender: 'Non-binary',
        city: 'Lipnica',
        country: 'Poland',
        orderId: 98,
      },
      {
        id: 'aa85c67e-a3ed-438e-b589-716ff8f23986',
        firstName: 'Angelia',
        lastName: 'Mance',
        email: 'amance2q@typepad.com',
        gender: 'Female',
        city: 'Svorónos',
        country: 'Greece',
        orderId: 99,
      },
      {
        id: '39d81e6c-ffb9-4336-b585-c7c2a4ef96d4',
        firstName: 'Gerladina',
        lastName: 'Stygall',
        email: 'gstygall2r@comcast.net',
        gender: 'Female',
        city: 'Stuttgart Stuttgart-Mitte',
        country: 'Germany',
        orderId: 100,
      },
    ],
    [],
  );

  const sortByFn: SortByFn<Data> = useMemo(
    () => (rawA, rawB) => {
      if (rawA.values.orderId < rawB.values.orderId) {
        return 1;
      }
      if (rawA.values.orderId > rawB.values.orderId) {
        return -1;
      }

      return 0;
    },
    [],
  );
  const columns: Column<Data>[] = useMemo(
    () => [
      {
        Header: 'ID',
        accessor: 'id', // accessor is the "key" in the data
        sortType: sortByFn,
      },
      {
        Header: 'First Name',
        accessor: 'firstName',
      },
      {
        Header: 'Last Name',
        accessor: 'lastName',
      },
      {
        Header: 'Email',
        accessor: 'email',
      },
      {
        Header: 'Gender',
        accessor: 'gender',
      },
      {
        Header: 'City',
        accessor: 'city',
      },
      {
        Header: 'Country',
        accessor: 'country',
      },
    ],
    [sortByFn],
  );

  return (
    <Layout>
      <Table columns={columns} data={data} />
    </Layout>
  );
};

export default TablePage;
